version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/tools/cmd/scraper"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"
