// Package hyperping provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package hyperping

// AcknowledgedByUser The user who acknowledged an outage.
type AcknowledgedByUser struct {
	Email string `json:"email"`
	Name  string `json:"name"`
	UUID  string `json:"uuid"`
}

// AddIncidentUpdateRequest Request body for adding an update to an incident.
type AddIncidentUpdateRequest struct {
	Date string `json:"date"`

	// Text Text that can be localized in multiple languages.
	Text LocalizedText `json:"text"`
	Type string        `json:"type"`
}

// AddSubscriberRequest Request body for adding a subscriber to a status page.
type AddSubscriberRequest struct {
	Email           *string `json:"email,omitempty"`
	Language        *string `json:"language,omitempty"`
	Phone           *string `json:"phone,omitempty"`
	TeamsWebhookURL *string `json:"teams_webhook_url,omitempty"`
	Type            string  `json:"type"`
}

// CreateHealthcheckRequest Request body for creating a healthcheck.
type CreateHealthcheckRequest struct {
	Cron             *string `json:"cron,omitempty"`
	EscalationPolicy *string `json:"escalation_policy,omitempty"`
	GracePeriodType  string  `json:"grace_period_type"`
	GracePeriodValue int     `json:"grace_period_value"`
	Name             string  `json:"name"`
	PeriodType       *string `json:"period_type,omitempty"`
	PeriodValue      *int    `json:"period_value,omitempty"`
	Timezone         *string `json:"timezone,omitempty"`
}

// CreateIncidentRequest Request body for creating an incident.
type CreateIncidentRequest struct {
	AffectedComponents []string `json:"affectedComponents,omitempty"`
	Date               string   `json:"date,omitempty"`
	StatusPages        []string `json:"statuspages"`

	// Text Text that can be localized in multiple languages.
	Text LocalizedText `json:"text"`

	// Title Text that can be localized in multiple languages.
	Title   LocalizedText              `json:"title"`
	Type    string                     `json:"type"`
	Updates []AddIncidentUpdateRequest `json:"updates,omitempty"`
}

// CreateMaintenanceRequest Request body for creating a maintenance window.
type CreateMaintenanceRequest struct {
	EndDate             string   `json:"end_date"`
	Monitors            []string `json:"monitors"`
	Name                string   `json:"name"`
	NotificationMinutes *int     `json:"notificationMinutes,omitempty"`
	NotificationOption  string   `json:"notificationOption,omitempty"`
	StartDate           string   `json:"start_date"`
	StatusPages         []string `json:"statuspages,omitempty"`

	// Text Text that can be localized in multiple languages.
	Text LocalizedText `json:"text,omitempty"`

	// Title Text that can be localized in multiple languages.
	Title LocalizedText `json:"title,omitempty"`
}

// CreateMonitorRequest Request body for creating a monitor.
type CreateMonitorRequest struct {
	AlertsWait         int             `json:"alerts_wait,omitempty"`
	CheckFrequency     int             `json:"check_frequency,omitempty"`
	DNSExpectedAnswer  *string         `json:"dns_expected_answer,omitempty"`
	DNSNameserver      *string         `json:"dns_nameserver,omitempty"`
	DNSRecordType      *string         `json:"dns_record_type,omitempty"`
	EscalationPolicy   string          `json:"escalation_policy,omitempty"`
	ExpectedStatusCode string          `json:"expected_status_code,omitempty"`
	FollowRedirects    *bool           `json:"follow_redirects,omitempty"`
	HTTPMethod         string          `json:"http_method,omitempty"`
	Name               string          `json:"name"`
	Paused             bool            `json:"paused,omitempty"`
	Port               int             `json:"port,omitempty"`
	ProjectUUID        string          `json:"projectUuid,omitempty"`
	Protocol           string          `json:"protocol"`
	Regions            []string        `json:"regions,omitempty"`
	RequestBody        *string         `json:"request_body,omitempty"`
	RequestHeaders     []RequestHeader `json:"request_headers,omitempty"`
	RequiredKeyword    string          `json:"required_keyword,omitempty"`
	URL                string          `json:"url"`
}

// CreateOutageRequest Request body for creating a manual outage.
type CreateOutageRequest struct {
	Description          string  `json:"description"`
	EndDate              string  `json:"endDate,omitempty"`
	EscalationPolicyUUID string  `json:"escalationPolicyUuid,omitempty"`
	MonitorUUID          string  `json:"monitorUuid"`
	OutageType           string  `json:"outageType"`
	Severity             *string `json:"severity,omitempty"`
	StartDate            string  `json:"startDate"`
	StatusCode           int     `json:"statusCode"`
	Summary              *string `json:"summary,omitempty"`
}

// CreateStatusPageRequest Request body for creating a status page.
type CreateStatusPageRequest struct {
	AccentColor           *string                                 `json:"accent_color,omitempty"`
	Authentication        *CreateStatusPageAuthenticationSettings `json:"authentication,omitempty"`
	AutoRefresh           *bool                                   `json:"auto_refresh,omitempty"`
	BannerHeader          *bool                                   `json:"banner_header,omitempty"`
	DefaultLanguage       *string                                 `json:"default_language,omitempty"`
	Description           *string                                 `json:"description,omitempty"`
	Favicon               *string                                 `json:"favicon,omitempty"`
	Font                  *string                                 `json:"font,omitempty"`
	GoogleAnalytics       *string                                 `json:"google_analytics,omitempty"`
	HideFromSearchEngines *bool                                   `json:"hide_from_search_engines,omitempty"`
	HidePoweredBy         *bool                                   `json:"hide_powered_by,omitempty"`
	Hostname              *string                                 `json:"hostname,omitempty"`
	Languages             []string                                `json:"languages,omitempty"`
	Logo                  *string                                 `json:"logo,omitempty"`
	LogoHeight            *string                                 `json:"logo_height,omitempty"`
	Name                  string                                  `json:"name"`
	Password              *string                                 `json:"password,omitempty"`
	Sections              []CreateStatusPageSection               `json:"sections,omitempty"`
	Subdomain             *string                                 `json:"subdomain,omitempty"`
	Subscribe             *CreateStatusPageSubscribeSettings      `json:"subscribe,omitempty"`
	Theme                 *string                                 `json:"theme,omitempty"`
	Website               *string                                 `json:"website,omitempty"`
}

// EscalationPolicyRef Escalation policy UUID and display name returned by the read API.
type EscalationPolicyRef struct {
	Name string `json:"name"`
	UUID string `json:"uuid"`
}

// EscalationPolicyReference Simplified escalation policy object included in outage and healthcheck responses.
type EscalationPolicyReference struct {
	AlertedSteps int    `json:"alertedSteps"`
	Name         string `json:"name"`
	TotalSteps   int    `json:"totalSteps"`
	UUID         string `json:"uuid"`
}

// Healthcheck A Hyperping healthcheck (cron job monitoring).
type Healthcheck struct {
	CreatedAt string `json:"createdAt,omitempty"`
	Cron      string `json:"cron,omitempty"`
	DueDate   string `json:"dueDate,omitempty"`

	// EscalationPolicy Simplified escalation policy object included in outage and healthcheck responses.
	EscalationPolicy *EscalationPolicyReference `json:"escalationPolicy,omitempty"`
	GracePeriod      int                        `json:"gracePeriod"`
	GracePeriodType  string                     `json:"gracePeriodType"`
	GracePeriodValue int                        `json:"gracePeriodValue"`
	IsDown           bool                       `json:"isDown"`
	IsPaused         bool                       `json:"isPaused"`
	LastLogEndDate   string                     `json:"lastLogEndDate,omitempty"`
	LastLogStartDate string                     `json:"lastLogStartDate,omitempty"`
	LastPing         string                     `json:"lastPing,omitempty"`
	Name             string                     `json:"name"`
	Period           int                        `json:"period"`
	PeriodType       string                     `json:"periodType,omitempty"`
	PeriodValue      *int                       `json:"periodValue,omitempty"`
	PingURL          string                     `json:"pingUrl"`
	Timezone         string                     `json:"timezone,omitempty"`
	Tz               string                     `json:"tz,omitempty"`
	UUID             string                     `json:"uuid"`
}

// Incident A Hyperping incident.
type Incident struct {
	AffectedComponents []string `json:"affectedComponents,omitempty"`
	Date               string   `json:"date,omitempty"`
	StatusPages        []string `json:"statuspages"`

	// Text Text that can be localized in multiple languages.
	Text LocalizedText `json:"text"`

	// Title Text that can be localized in multiple languages.
	Title   LocalizedText    `json:"title"`
	Type    string           `json:"type"`
	Updates []IncidentUpdate `json:"updates,omitempty"`
	UUID    string           `json:"uuid"`
}

// IncidentUpdate An update entry on an incident.
type IncidentUpdate struct {
	Date string `json:"date"`

	// Text Text that can be localized in multiple languages.
	Text LocalizedText `json:"text"`
	Type string        `json:"type"`
	UUID string        `json:"uuid"`
}

// ListMonitorReportsResponse Paginated list of monitor reports.
type ListMonitorReportsResponse struct {
	Monitors []MonitorReport `json:"monitors"`

	// Period Time period for a monitor report.
	Period ReportPeriod `json:"period"`
}

// LocalizedText Text that can be localized in multiple languages.
type LocalizedText struct {
	De string `json:"de,omitempty"`
	En string `json:"en,omitempty"`
	Es string `json:"es,omitempty"`
	Fr string `json:"fr,omitempty"`
	It string `json:"it,omitempty"`
	Ja string `json:"ja,omitempty"`
	Nl string `json:"nl,omitempty"`
	Pt string `json:"pt,omitempty"`
	Ru string `json:"ru,omitempty"`
	Zh string `json:"zh,omitempty"`
}

// Maintenance A Hyperping maintenance window.
type Maintenance struct {
	BulkUUID            *string  `json:"bulkUuid,omitempty"`
	CreatedAt           string   `json:"createdAt,omitempty"`
	CreatedBy           string   `json:"createdBy,omitempty"`
	EndDate             *string  `json:"end_date,omitempty"`
	Monitors            []string `json:"monitors"`
	Name                string   `json:"name"`
	NotificationMinutes *int     `json:"notificationMinutes,omitempty"`
	NotificationOption  string   `json:"notificationOption,omitempty"`
	StartDate           *string  `json:"start_date,omitempty"`
	Status              string   `json:"status,omitempty"`
	StatusPages         []string `json:"statuspages,omitempty"`

	// Text Text that can be localized in multiple languages.
	Text     LocalizedText `json:"text,omitempty"`
	Timezone string        `json:"timezone,omitempty"`

	// Title Text that can be localized in multiple languages.
	Title   LocalizedText       `json:"title,omitempty"`
	Updates []MaintenanceUpdate `json:"updates,omitempty"`
	UUID    string              `json:"uuid"`
}

// MaintenanceUpdate An update entry on a maintenance window.
type MaintenanceUpdate struct {
	Date string `json:"date"`

	// Text Text that can be localized in multiple languages.
	Text LocalizedText `json:"text"`
}

// MonitorReference Simplified monitor object included in outage responses.
type MonitorReference struct {
	Name     string `json:"name"`
	Protocol string `json:"protocol"`
	URL      string `json:"url"`
	UUID     string `json:"uuid"`
}

// MonitorReport Report for a monitor.
type MonitorReport struct {
	MTTR          int    `json:"mttr,omitempty"`
	MTTRFormatted string `json:"mttrFormatted,omitempty"`
	Name          string `json:"name"`

	// Outages Statistics about outages in a report.
	Outages OutageStats `json:"outages"`

	// Period Time period for a monitor report.
	Period   ReportPeriod `json:"period"`
	Protocol string       `json:"protocol"`
	SLA      float64      `json:"sla"`
	UUID     string       `json:"uuid"`
}

// Outage A Hyperping outage (system-generated monitor failure).
type Outage struct {
	AcknowledgedAt *string `json:"acknowledgedAt,omitempty"`

	// AcknowledgedBy The user who acknowledged an outage.
	AcknowledgedBy     *AcknowledgedByUser `json:"acknowledgedBy,omitempty"`
	ConfirmedLocations string              `json:"confirmedLocations"`
	Description        string              `json:"description"`
	DetectedLocation   string              `json:"detectedLocation"`
	DurationMs         int                 `json:"durationMs"`
	EndDate            *string             `json:"endDate,omitempty"`

	// EscalationPolicy Simplified escalation policy object included in outage and healthcheck responses.
	EscalationPolicy *EscalationPolicyReference `json:"escalationPolicy,omitempty"`
	IsResolved       bool                       `json:"isResolved"`

	// Monitor Simplified monitor object included in outage responses.
	Monitor    MonitorReference `json:"monitor"`
	OutageType string           `json:"outageType"`
	Severity   string           `json:"severity,omitempty"`
	StartDate  string           `json:"startDate"`
	StatusCode int              `json:"statusCode"`
	Summary    string           `json:"summary,omitempty"`
	UUID       string           `json:"uuid"`
}

// OutageDetail Details about a specific outage in a report.
type OutageDetail struct {
	Duration          int    `json:"duration,omitempty"`
	DurationFormatted string `json:"durationFormatted,omitempty"`
	EndDate           string `json:"endDate"`
	StartDate         string `json:"startDate"`
}

// OutageStats Statistics about outages in a report.
type OutageStats struct {
	Count                  int            `json:"count"`
	Details                []OutageDetail `json:"details"`
	LongestOutage          int            `json:"longestOutage"`
	LongestOutageFormatted string         `json:"longestOutageFormatted"`
	TotalDowntime          int            `json:"totalDowntime"`
	TotalDowntimeFormatted string         `json:"totalDowntimeFormatted"`
}

// ReportPeriod Time period for a monitor report.
type ReportPeriod struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// RequestHeader A single HTTP request header.
type RequestHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// StatusPage A Hyperping status page.
type StatusPage struct {
	HostedSubdomain   string              `json:"hostedsubdomain"`
	Hostname          string              `json:"hostname,omitempty"`
	Name              string              `json:"name"`
	PasswordProtected bool                `json:"password_protected"`
	Sections          []StatusPageSection `json:"sections"`

	// Settings Settings for a status page.
	Settings StatusPageSettings `json:"settings"`
	URL      string             `json:"url"`
	UUID     string             `json:"uuid"`
}

// StatusPagePaginatedResponse Paginated list of status pages.
type StatusPagePaginatedResponse struct {
	HasNextPage    bool         `json:"hasNextPage"`
	Page           int          `json:"page"`
	ResultsPerPage int          `json:"resultsPerPage"`
	StatusPages    []StatusPage `json:"statuspages"`
	Total          int          `json:"total"`
}

// StatusPageSection A section on a status page.
type StatusPageSection struct {
	IsSplit  bool                `json:"is_split"`
	Name     map[string]string   `json:"name"`
	Services []StatusPageService `json:"services"`
}

// StatusPageService A service (monitor or component) in a status page section.
type StatusPageService struct {
	Description       map[string]string   `json:"description,omitempty"`
	ID                *FlexibleString     `json:"id,omitempty"`
	IsGroup           bool                `json:"is_group"`
	Name              map[string]string   `json:"name"`
	Services          []StatusPageService `json:"services,omitempty"`
	ShowResponseTimes bool                `json:"show_response_times"`
	ShowUptime        bool                `json:"show_uptime"`
	UUID              string              `json:"uuid,omitempty"`
}

// StatusPageSettings Settings for a status page.
type StatusPageSettings struct {
	AccentColor           string                           `json:"accent_color"`
	Authentication        StatusPageAuthenticationSettings `json:"authentication"`
	AutoRefresh           bool                             `json:"auto_refresh"`
	BannerHeader          bool                             `json:"banner_header"`
	DefaultLanguage       string                           `json:"default_language"`
	Description           map[string]string                `json:"description,omitempty"`
	Favicon               string                           `json:"favicon,omitempty"`
	Font                  string                           `json:"font"`
	GoogleAnalytics       string                           `json:"google_analytics,omitempty"`
	HideFromSearchEngines bool                             `json:"hide_from_search_engines"`
	HidePoweredBy         bool                             `json:"hide_powered_by"`
	Languages             []string                         `json:"languages"`
	Logo                  string                           `json:"logo,omitempty"`
	LogoHeight            string                           `json:"logo_height"`
	Name                  string                           `json:"name"`
	Subscribe             StatusPageSubscribeSettings      `json:"subscribe"`
	Theme                 string                           `json:"theme"`
	Website               string                           `json:"website,omitempty"`
}

// StatusPageSubscriber A subscriber to a status page.
type StatusPageSubscriber struct {
	CreatedAt    string  `json:"created_at"`
	Email        *string `json:"email,omitempty"`
	ID           int     `json:"id"`
	Language     string  `json:"language"`
	Phone        *string `json:"phone,omitempty"`
	SlackChannel *string `json:"slack_channel,omitempty"`
	Type         string  `json:"type"`
	Value        string  `json:"value"`
}

// UpdateHealthcheckRequest Request body for updating a healthcheck.
type UpdateHealthcheckRequest struct {
	Cron             *string `json:"cron,omitempty"`
	EscalationPolicy *string `json:"escalation_policy,omitempty"`
	GracePeriodType  *string `json:"grace_period_type,omitempty"`
	GracePeriodValue *int    `json:"grace_period_value,omitempty"`
	Name             *string `json:"name,omitempty"`
	PeriodType       *string `json:"period_type,omitempty"`
	PeriodValue      *int    `json:"period_value,omitempty"`
	Timezone         *string `json:"timezone,omitempty"`
}

// UpdateIncidentRequest Request body for updating an incident.
type UpdateIncidentRequest struct {
	AffectedComponents *[]string `json:"affectedComponents,omitempty"`
	StatusPages        *[]string `json:"statuspages,omitempty"`

	// Text Text that can be localized in multiple languages.
	Text *LocalizedText `json:"text,omitempty"`

	// Title Text that can be localized in multiple languages.
	Title   *LocalizedText             `json:"title,omitempty"`
	Type    *string                    `json:"type,omitempty"`
	Updates []AddIncidentUpdateRequest `json:"updates,omitempty"`
}

// UpdateMaintenanceRequest Request body for updating a maintenance window.
type UpdateMaintenanceRequest struct {
	EndDate             *string   `json:"end_date,omitempty"`
	Monitors            *[]string `json:"monitors,omitempty"`
	Name                *string   `json:"name,omitempty"`
	NotificationMinutes *int      `json:"notificationMinutes,omitempty"`
	NotificationOption  *string   `json:"notificationOption,omitempty"`
	StartDate           *string   `json:"start_date,omitempty"`
	StatusPages         *[]string `json:"statuspages,omitempty"`

	// Text Text that can be localized in multiple languages.
	Text *LocalizedText `json:"text,omitempty"`

	// Title Text that can be localized in multiple languages.
	Title *LocalizedText `json:"title,omitempty"`
}

// UpdateMonitorRequest Request body for updating a monitor.
type UpdateMonitorRequest struct {
	AlertsWait         *int             `json:"alerts_wait,omitempty"`
	CheckFrequency     *int             `json:"check_frequency,omitempty"`
	DNSExpectedAnswer  *string          `json:"dns_expected_answer,omitempty"`
	DNSNameserver      *string          `json:"dns_nameserver,omitempty"`
	DNSRecordType      *string          `json:"dns_record_type,omitempty"`
	EscalationPolicy   *string          `json:"escalation_policy,omitempty"`
	ExpectedStatusCode *string          `json:"expected_status_code,omitempty"`
	FollowRedirects    *bool            `json:"follow_redirects,omitempty"`
	HTTPMethod         *string          `json:"http_method,omitempty"`
	Name               *string          `json:"name,omitempty"`
	Paused             *bool            `json:"paused,omitempty"`
	Port               *int             `json:"port,omitempty"`
	ProjectUUID        *string          `json:"projectUuid,omitempty"`
	Protocol           *string          `json:"protocol,omitempty"`
	Regions            *[]string        `json:"regions,omitempty"`
	RequestBody        *string          `json:"request_body,omitempty"`
	RequestHeaders     *[]RequestHeader `json:"request_headers,omitempty"`
	RequiredKeyword    *string          `json:"required_keyword,omitempty"`
	URL                *string          `json:"url,omitempty"`
}

// UpdateStatusPageRequest Request body for updating a status page.
type UpdateStatusPageRequest struct {
	AccentColor           *string                                 `json:"accent_color,omitempty"`
	Authentication        *CreateStatusPageAuthenticationSettings `json:"authentication,omitempty"`
	AutoRefresh           *bool                                   `json:"auto_refresh,omitempty"`
	BannerHeader          *bool                                   `json:"banner_header,omitempty"`
	DefaultLanguage       *string                                 `json:"default_language,omitempty"`
	Description           *string                                 `json:"description,omitempty"`
	Favicon               *string                                 `json:"favicon,omitempty"`
	Font                  *string                                 `json:"font,omitempty"`
	GoogleAnalytics       *string                                 `json:"google_analytics,omitempty"`
	HideFromSearchEngines *bool                                   `json:"hide_from_search_engines,omitempty"`
	HidePoweredBy         *bool                                   `json:"hide_powered_by,omitempty"`
	Hostname              *string                                 `json:"hostname,omitempty"`
	Languages             []string                                `json:"languages,omitempty"`
	Logo                  *string                                 `json:"logo,omitempty"`
	LogoHeight            *string                                 `json:"logo_height,omitempty"`
	Name                  *string                                 `json:"name,omitempty"`
	Password              *string                                 `json:"password,omitempty"`
	Sections              []CreateStatusPageSection               `json:"sections,omitempty"`
	Subdomain             *string                                 `json:"subdomain,omitempty"`
	Subscribe             *CreateStatusPageSubscribeSettings      `json:"subscribe,omitempty"`
	Theme                 *string                                 `json:"theme,omitempty"`
	Website               *string                                 `json:"website,omitempty"`
}
